# Generated by Django 5.2.4 on 2025-08-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('languages_known', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('father_name', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=255)),
                ('interests', models.TextField()),
                ('goals', models.TextField()),
            ],
        ),
    ]
